- .gitignore
- development/less/pages/catalog/item/catalog-item.less
добавил переменную @{img} в путь к shadow-6.png , 
упорядочил содержимое в .gitignore и добавил комментарии
> добавил переменную @{img} в путь к shadow-6.png

- development/AMMA-22.html
- development/less/legacy-css/base.less
- development/less/legacy-css/filter.responsive.less
- development/less/legacy-css/style_new.less
- development/less/pages/catalog/filter/filter-group.less
Задача https://jira.zoloto585.ru/browse/AMMA-22
(Правки шаблона и скриптов на гитлабе в ветке AMMA-22)
---
1) Сделать горизонтальный скролл для выбранных фасетов фильтра
2) уменьшить область пагинации по высоте.
3) скрыть "Хлебные крошки" на десктоп в каталоге
4) скрыть пока блок "ПОКАЗАНО: 16 ИЗ 171"
> AMMA-22: правки верстки фильтра и каталога

- development/less/legacy-css/style_new.less
- development/less/pages/catalog/filter/filter-group.less
- development/less/pages/catalog/filter/filter-section.less
не большие правки стилей фильтра и пагинации
> AMMA-22: не большие правки стилей фильтра и пагинации

- gulpfile.js
watch бесконечно работал из файлов z585-all-list.local.less, добавил исключение и таски только для local
> gulpfile: watch fix

- development/AMMA-21.html
- development/less/layout/header/header-middle/header-middle.less
- development/less/layout/header/header-top/header-top.less
- development/less/layout/header/header-top/overtop-banner.less
- development/less/scaffolding/layout__header.less
Баннер над шапкой
Задача https://jira.zoloto585.ru/browse/AMMA-21
> Баннер над шапкой Amma 21

- development/AMMA-15-v2.html
- development/less/layout/header/header-middle/header-middle.less
- development/less/mixins/@breakpoints.less
задача https://jira.zoloto585.ru/browse/AMMA-15
> AMMA-15: правка верстки шапки и футера (моб)

- development/catalog.html
- development/htmls/pages/catalog/catalog-list.html
- development/less/mixins/@fonts.less
- development/less/pages/catalog/overtop-promo.less
- development/less/scaffolding/pages__catalog.less
Для акций нам нужно сверстать всплывающую плашку с импут полем для ввода бонусной карт
https://jira.zoloto585.ru/browse/AMMA-30
> AMMA-30: сверстать акционную плашку для каталога

- development/less/pages/shop/shop-info.less
- development/less/pages/shop/shop-location.less
- pr/2017/_20002.md
Описание работ https://github.com/liss38/frontend/blob/_20002/pr/2017/_20002.md
> _20002. Мелкие правки по странице СТРАНИЦА МАГАЗИНОВ

- gulpfile.js
- pr/2017/_10001.md
Задача в жире https://jira.zoloto585.ru/browse/AMMA-33
_10001. Gulp. Найти и настроить плагин, который будет копировать производные js-файлы для прода в папку продкшна ./production gitHub-репозитория
> Задача _10001

- development/less/mixins/@breakpoints.less
- development/less/pages/catalog/item/catalog-item.less
- pr/2017/_21011.md
фиксы задачи https://jira.zoloto585.ru/browse/AMMA-35
> AMMA-35-fix

- development/less/pages/catalog/item/catalog-list.less
Правки стилей по задаче https://jira.zoloto585.ru/browse/AMMA-35
> AMMA-35-fix2: less

- development/less/pages/catalog/item/catalog-item.less
Правки стилей по задаче https://jira.zoloto585.ru/browse/AMMA-35
> AMMA-35-fix3

- development/less/pages/catalog/item/catalog-list.less
задача в жире https://jira.zoloto585.ru/browse/AMMA-40
> AMMA-40: скорректировать разметку в карточке товара

- development/less/pages/catalog/item/catalog-item.less
Задача https://jira.zoloto585.ru/browse/AMMA-46
> AMMA-46: перенести расположение "НЕТ В НАЛИЧИИ" в карточках листинга

- development/less/legacy-css/base.less
- development/less/legacy-css/filter.less
- development/less/legacy-css/filter.responsive.less
https://jira.zoloto585.ru/browse/AMMA-52
> AMMA-52: убрать верхнюю пагинацию и хрошки на тач версии

- development/less/legacy-css/filter.less
из задачи https://jira.zoloto585.ru/browse/AMMA-52
> AMMA-52: фикс дропдауна в фильтре, добавлен скролл и фикс. высота

- development/less/pages/catalog/item/catalog-item.less
задача https://jira.zoloto585.ru/browse/AMMA-57
> _21014: добавить видео баннеры в сетку продуктов

- development/less/pages/reg-card/content.less
- development/less/pages/reg-card/tabs.less
AMMA-55, быстрые фиксы для мобильной версии,
https://jira.zoloto585.ru/browse/AMMA-55
> _20008. AMMA-55, быстрые фиксы для мобильной версии

- development/less/pages/reg-card/content.less
- development/less/pages/reg-card/header.less
- development/less/pages/reg-card/main.less
- development/less/pages/reg-card/tabs.less
Задача https://jira.zoloto585.ru/browse/AMMA-59
Подзадача https://jira.zoloto585.ru/browse/AMMA-60
Правки и адаптивные стили
> AMMA-59: скорректировать верстку страницы регистрации бонусных карт

- development/less/pages/product-card/pcard-order-step-1/pcard-order-promo-forms--shame.less
Reverts zoloto585gold/frontend#98
> Revert "страница товара -> попап бронирования -> первый шаг: съехала красная …"

- development/less/pages/product-card/pcard-order-step-1/pcard-order-promo-forms--shame.less
_20010. Страница товара -> попап бронирования -> первый шаг: съехала красная кнопка
> _20010. Страница товара -> попап бронирования -> первый шаг: съехала красная кнопка

- development/less/pages/product-card/pcard-store.less
кнопка купить и блок с результатом в карточке товаров
нужен для корзины AMMA-78
> css: buy-btn

- development/htmls/pages/catalog/catalog-list-item.html
- development/less/pages/catalog/item/catalog-item.less
- development/less/pages/catalog/item/catalog-list.less
Reverts zoloto585gold/frontend#123
> Revert "ESHOP-127 увеличить расстояние между ценами в каталоге"

- development/js/app/z585.basket.js
> Amma 78 f1

- development/htmls/basket-step2.tmpl
- development/htmls/pages/basket/step2/basket-list.html
- development/htmls/pages/basket/step2/basket-map.html
- development/js/app/z585.basket.js
- development/js/app/z585.yamaps.js
- development/js/pages/basket-page/basket.js
- development/less/pages/basket/basket-shops.less
- development/less/pages/product-card/pcard-store.less
- development/less/scaffolding/pages__basket.less
> Amma 78 f2

- development/htmls/pcard.tmpl
- development/less/pages/product-card/pcard--shame.less
Первый pull request, в качестве обучения.
> Добавил стиль подчеркивания и комментарии к файлам
